version: '3.8'

services:
  nostria-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nostria-app
    restart: unless-stopped
    ports:
      - '8888:4000'
    environment:
      - NODE_ENV=development
      - PORT=4000
    # Optional volumes for development (uncomment if needed)
    # volumes:
    #   - ./src:/app/src
    networks:
      - nostria-network

networks:
  nostria-network:
    driver: bridge
