/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UsersByReleaseChannel } from '../../models/users-by-release-channel';

export interface SettingsAdminReleaseChannelChannelGet$Params {

/**
 * Release channel to query
 */
  channel: 'stable' | 'beta' | 'alpha';
}

export function settingsAdminReleaseChannelChannelGet(http: HttpClient, rootUrl: string, params: SettingsAdminReleaseChannelChannelGet$Params, context?: HttpContext): Observable<StrictHttpResponse<UsersByReleaseChannel>> {
  const rb = new RequestBuilder(rootUrl, settingsAdminReleaseChannelChannelGet.PATH, 'get');
  if (params) {
    rb.path('channel', params.channel, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UsersByReleaseChannel>;
    })
  );
}

settingsAdminReleaseChannelChannelGet.PATH = '/settings/admin/release-channel/{channel}';
