/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuccessResponse } from '../../models/success-response';
import { UserSettingsUpdate } from '../../models/user-settings-update';

export interface SettingsPubkeyPost$Params {

/**
 * User's public key (hexadecimal format)
 */
  pubkey: string;
      body: UserSettingsUpdate
}

export function settingsPubkeyPost(http: HttpClient, rootUrl: string, params: SettingsPubkeyPost$Params, context?: HttpContext): Observable<StrictHttpResponse<SuccessResponse>> {
  const rb = new RequestBuilder(rootUrl, settingsPubkeyPost.PATH, 'post');
  if (params) {
    rb.path('pubkey', params.pubkey, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuccessResponse>;
    })
  );
}

settingsPubkeyPost.PATH = '/settings/{pubkey}';
