/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BackupJobResponse } from '../../models/backup-job-response';

export interface BackupJobIdGet$Params {

/**
 * The backup job ID
 */
  jobId: string;
}

export function backupJobIdGet(http: HttpClient, rootUrl: string, params: BackupJobIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<BackupJobResponse>> {
  const rb = new RequestBuilder(rootUrl, backupJobIdGet.PATH, 'get');
  if (params) {
    rb.path('jobId', params.jobId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BackupJobResponse>;
    })
  );
}

backupJobIdGet.PATH = '/backup/{jobId}';
