/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BackupJobResponse } from '../../models/backup-job-response';
import { CreateBackupJobRequest } from '../../models/create-backup-job-request';

export interface BackupPost$Params {
      body: CreateBackupJobRequest
}

export function backupPost(http: HttpClient, rootUrl: string, params: BackupPost$Params, context?: HttpContext): Observable<StrictHttpResponse<BackupJobResponse>> {
  const rb = new RequestBuilder(rootUrl, backupPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BackupJobResponse>;
    })
  );
}

backupPost.PATH = '/backup';
