/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AccountDto {

  /**
   * User's email address
   */
  email?: string | null;

  /**
   * Last login date
   */
  lastLoginDate?: string | null;

  /**
   * User's public key
   */
  pubkey?: string;

  /**
   * Account creation date
   */
  signupDate?: string;

  /**
   * User's username
   */
  username?: string | null;
}
