/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Entitlements } from '../models/entitlements';
import { Tier } from '../models/tier';
export interface Account {
  entitlements?: Entitlements;

  /**
   * Subscription expiry date
   */
  expires?: number | null;

  /**
   * Last login date
   */
  lastLoginDate?: number | null;

  /**
   * User's public key
   */
  pubkey?: string;

  /**
   * Account creation date
   */
  signupDate?: number;
  tier?: Tier;

  /**
   * User's username
   */
  username?: string | null;
}
