/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AddAccountRequest {

  /**
   * Payment Id for the premium payment
   */
  paymentId?: string | null;

  /**
   * User's public key
   */
  pubkey: string;

  /**
   * User's username
   */
  username?: string | null;
}
