/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AddAccountRequest {

  /**
   * User's email address
   */
  email?: string | null;

  /**
   * User's public key
   */
  pubkey: string;
}
