/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PublicAccountDto } from '../models/public-account-dto';
export interface ApiResponse {

  /**
   * Optional message about the response
   */
  message?: string;
  result?: PublicAccountDto;

  /**
   * Whether the request was successful
   */
  success?: boolean;
}
