/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PublicAccount } from '../models/public-account';
export interface ApiResponse {

  /**
   * Optional message about the response
   */
  message?: string;
  result?: PublicAccount;

  /**
   * Whether the request was successful
   */
  success: boolean;
}
