/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Type of backup to perform
 */
export enum BackupType {
  Full = 'full',
  Incremental = 'incremental',
  Selective = 'selective'
}
