/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BackupJobStatus } from '../models/backup-job-status';
import { BackupType } from '../models/backup-type';
export interface BackupJobResponse {
  backupType?: BackupType;
  completedAt?: number | null;
  errorMessage?: string | null;

  /**
   * When the backup download link expires
   */
  expires?: number | null;

  /**
   * Unique identifier for the backup job
   */
  id?: string;
  metadata?: {
} | null;
  requestedAt?: number;

  /**
   * Download URL for completed backup (expires after some time)
   */
  resultUrl?: string | null;
  scheduledAt?: number | null;
  startedAt?: number | null;
  status?: BackupJobStatus;
}
