/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BackupType } from '../models/backup-type';
export interface CreateBackupJobRequest {
  backupType: BackupType;
  metadata?: {

/**
 * Optional description for the backup
 */
'description'?: string;
[key: string]: any;
};

  /**
   * Optional scheduled execution time (defaults to immediate)
   */
  scheduledAt?: number;
}
