/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreatePaymentRequest {

  /**
   * Billing cycle
   */
  billingCycle: 'monthly' | 'quarterly' | 'yearly';

  /**
   * Price in USD cents
   */
  price: number;

  /**
   * User's public key in npub format
   */
  pubkey: string;

  /**
   * Subscription tier name
   */
  tierName: 'free' | 'premium' | 'premium_plus';
}
