/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FeatureWithLabel } from '../models/feature-with-label';
export interface Entitlements {
  features?: Array<FeatureWithLabel>;
  notificationsPerDay?: number;
}
