/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Error {

  /**
   * Error message
   */
  error?: string;

  /**
   * Additional error details
   */
  message?: string | null;
}
