/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Subscription feature
 */
export enum Feature {
  BasicWebpush = 'BASIC_WEBPUSH',
  CommunitySupport = 'COMMUNITY_SUPPORT',
  Username = 'USERNAME',
  AdvancedFiltering = 'ADVANCED_FILTERING',
  PrioritySupport = 'PRIORITY_SUPPORT',
  CustomTemplates = 'CUSTOM_TEMPLATES',
  ApiAccess = 'API_ACCESS',
  Webhook = 'WEBHOOK',
  Analytics = 'ANALYTICS'
}
