/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Subscription feature
 */
export enum Feature {
  BasicWebpush = 'BASIC_WEBPUSH',
  CommunitySupport = 'COMMUNITY_SUPPORT',
  Username = 'USERNAME',
  Newsletter = 'NEWSLETTER',
  Storage1gb = 'STORAGE_1GB',
  Storage5gb = 'STORAGE_5GB',
  Storage50gb = 'STORAGE_50GB',
  DualPostX10 = 'DUAL_POST_X_10',
  Analytics = 'ANALYTICS',
  CloudBackupComingSoon = 'CLOUD_BACKUP_COMING_SOON',
  Memos = 'MEMOS',
  Youtube = 'YOUTUBE',
  ExtraBackupFeatures = 'EXTRA_BACKUP_FEATURES'
}
