/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Feature } from '../models/feature';
export interface FeatureWithLabel {
  key: Feature;

  /**
   * Human-readable description of the feature
   */
  label?: string;
}
