/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificationRequest {

  /**
   * Template arguments for legacy template-based notifications
   */
  args?: {
[key: string]: any;
};

  /**
   * Notification body text (required for direct format)
   */
  body?: string;

  /**
   * Notification icon URL (optional, defaults to Nostria icon)
   */
  icon?: string;

  /**
   * Array of user public keys to send notifications to. If empty, sends to all users.
   */
  pubkeys?: Array<string>;

  /**
   * Template name for legacy template-based notifications
   */
  template?: string;

  /**
   * Notification title (required for direct format)
   */
  title?: string;

  /**
   * URL to open when notification is clicked
   */
  url?: string;
}
