/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificationStatus {

  /**
   * Number of registered devices
   */
  deviceCount?: number;

  /**
   * Whether user has active push subscriptions
   */
  hasSubscription?: boolean;

  /**
   * Whether user has premium subscription
   */
  isPremium?: boolean;
  notifications?: {

/**
 * Number of notifications sent in last 24 hours
 */
'count24h'?: number;

/**
 * Daily notification limit for user's tier
 */
'dailyLimit'?: number;

/**
 * Remaining notifications for today
 */
'remaining'?: number;
};

  /**
   * User's public key
   */
  pubkey?: string;

  /**
   * User notification settings
   */
  settings?: {

/**
 * Whether notifications are enabled
 */
'enabled'?: boolean;
};
}
