/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificationData {

  /**
   * Notification body text
   */
  body?: string;

  /**
   * Additional notification data
   */
  data?: {
[key: string]: any;
};

  /**
   * Notification icon URL
   */
  icon?: string;

  /**
   * Notification title
   */
  title?: string;
}
