/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Payment {

  /**
   * Expiry date
   */
  expiresAt: string;

  /**
   * Invoice ID
   */
  id: string;

  /**
   * LN invoice
   */
  lnInvoice: string;

  /**
   * Payment status
   */
  status: 'pending' | 'expired' | 'paid';
}
