/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Price {

  /**
   * Currency code (e.g., USD)
   */
  currency?: string;

  /**
   * Price in cents
   */
  priceCents?: number;
}
