/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Price } from '../models/price';
export interface Pricing {
  monthly?: Price;
  quarterly?: Price;
  yearly?: Price;
}
