/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PublicAccount {

  /**
   * Whether the account is active
   */
  isActive?: boolean;

  /**
   * User's public key
   */
  pubkey?: string;

  /**
   * Account creation date
   */
  signupDate?: string;

  /**
   * User's subscription tier
   */
  tier?: string;
}
