/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PushSubscription {

  /**
   * Push service endpoint URL
   */
  endpoint: string;
  keys: {

/**
 * P256DH key for encryption
 */
'p256dh': string;

/**
 * Auth secret for encryption
 */
'auth': string;
};

  /**
   * Browser user agent string
   */
  userAgent?: string;
}
