/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserSettingsResponse } from '../models/user-settings-response';
export interface SuccessResponse {
  data?: UserSettingsResponse;

  /**
   * Success message
   */
  message?: string;

  /**
   * Operation success status
   */
  success?: boolean;
}
