/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum Tier {
  Free = 'free',
  Basic = 'basic',
  Premium = 'premium',
  PremiumPlus = 'premium_plus'
}
