/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateAccountRequest {

  /**
   * User's email address
   */
  email?: string | null;

  /**
   * User's username
   */
  username?: string | null;
}
