/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserSettingsUpdate {

  /**
   * Release channel preference for app updates
   */
  releaseChannel?: 'stable' | 'beta' | 'alpha';

  /**
   * Whether social sharing features are enabled
   */
  socialSharing?: boolean;
}
