/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UsersByReleaseChannel {
  data?: {

/**
 * The queried release channel
 */
'releaseChannel'?: string;

/**
 * Number of users in this channel
 */
'userCount'?: number;

/**
 * Array of user public keys
 */
'users'?: Array<string>;
};

  /**
   * Operation result message
   */
  message?: string;

  /**
   * Operation success status
   */
  success?: boolean;
}
