/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserSettingsResponse {

  /**
   * Settings creation timestamp
   */
  created?: number;

  /**
   * User's public key
   */
  pubkey?: string;

  /**
   * Social sharing preference
   */
  socialSharing?: boolean;

  /**
   * Settings last update timestamp
   */
  updated?: number;
}
