/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface VapidKey {

  /**
   * Public VAPID key for Web Push notifications
   */
  key?: string;
}
