/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ServiceStatus } from '../../models/service-status';

export interface StatusGet$Params {
}

export function statusGet(http: HttpClient, rootUrl: string, params?: StatusGet$Params, context?: HttpContext): Observable<StrictHttpResponse<ServiceStatus>> {
  const rb = new RequestBuilder(rootUrl, statusGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ServiceStatus>;
    })
  );
}

statusGet.PATH = '/status';
