/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PushSubscription } from '../../models/push-subscription';

export interface SubscriptionWebpushPubkeyPost$Params {

/**
 * User's public key (hexadecimal format)
 */
  pubkey: string;
      body: PushSubscription
}

export function subscriptionWebpushPubkeyPost(http: HttpClient, rootUrl: string, params: SubscriptionWebpushPubkeyPost$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'success'?: boolean;
'message'?: string;
}>> {
  const rb = new RequestBuilder(rootUrl, subscriptionWebpushPubkeyPost.PATH, 'post');
  if (params) {
    rb.path('pubkey', params.pubkey, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'success'?: boolean;
      'message'?: string;
      }>;
    })
  );
}

subscriptionWebpushPubkeyPost.PATH = '/subscription/webpush/{pubkey}';
