/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AccountDto } from '../../models/account-dto';
import { AddAccountRequest } from '../../models/add-account-request';

export interface AddAccount$Params {
      body: AddAccountRequest
}

export function addAccount(http: HttpClient, rootUrl: string, params: AddAccount$Params, context?: HttpContext): Observable<StrictHttpResponse<AccountDto>> {
  const rb = new RequestBuilder(rootUrl, addAccount.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AccountDto>;
    })
  );
}

addAccount.PATH = '/account';
