/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PublicAccountDto } from '../../models/public-account-dto';

export interface GetPublicAccount$Params {

/**
 * User's public key in npub format or a username
 */
  pubkeyOrUsername: string;
}

export function getPublicAccount(http: HttpClient, rootUrl: string, params: GetPublicAccount$Params, context?: HttpContext): Observable<StrictHttpResponse<PublicAccountDto>> {
  const rb = new RequestBuilder(rootUrl, getPublicAccount.PATH, 'get');
  if (params) {
    rb.path('pubkeyOrUsername', params.pubkeyOrUsername, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PublicAccountDto>;
    })
  );
}

getPublicAccount.PATH = '/account/{pubkeyOrUsername}';
