/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TierDetails } from '../../models/tier-details';

export interface GetTiers$Params {
}

export function getTiers(http: HttpClient, rootUrl: string, params?: GetTiers$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: TierDetails;
}>> {
  const rb = new RequestBuilder(rootUrl, getTiers.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      [key: string]: TierDetails;
      }>;
    })
  );
}

getTiers.PATH = '/account/tiers';
