/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NotificationStatus } from '../../models/notification-status';

export interface NotificationStatusPubkeyGet$Params {

/**
 * User's public key (hexadecimal format)
 */
  pubkey: string;
}

export function notificationStatusPubkeyGet(http: HttpClient, rootUrl: string, params: NotificationStatusPubkeyGet$Params, context?: HttpContext): Observable<StrictHttpResponse<NotificationStatus>> {
  const rb = new RequestBuilder(rootUrl, notificationStatusPubkeyGet.PATH, 'get');
  if (params) {
    rb.path('pubkey', params.pubkey, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NotificationStatus>;
    })
  );
}

notificationStatusPubkeyGet.PATH = '/notification/status/{pubkey}';
