/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Payment } from '../../models/payment';

export interface GetPayment$Params {
  /**
   * Payment id
   */
  paymentId: string;
  pubkey: string;
}

export function getPayment(http: HttpClient, rootUrl: string, params: GetPayment$Params, context?: HttpContext): Observable<StrictHttpResponse<Payment>> {
  const rb = new RequestBuilder(rootUrl, getPayment.PATH, 'get');
  if (params) {
    rb.path('pubkey', params.pubkey, {});
    rb.path('paymentId', params.paymentId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Payment>;
    })
  );
}

getPayment.PATH = '/payment/{pubkey}/{paymentId}';
