name: Android Build

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Java for Android build
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Decode keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 -d > android.keystore
          ls -la android.keystore

      - name: Generate Android TWA project
        run: |
          echo "Current twa-manifest.json signing key path:"
          grep -A 3 '"signingKey"' twa-manifest.json

          # Use bubblewrap Docker container to generate the Android project from the manifest
          docker run --rm -v $(pwd):/workspace -w /workspace ghcr.io/googlechromelabs/bubblewrap:latest update --skipVersionUpgrade          echo "Bubblewrap update completed"

          # Verify the Android project was created
          echo "Checking if Android project files exist..."
          ls -la
          if [ -f "build.gradle" ] && [ -f "gradlew" ] && [ -d "app" ]; then
            echo "Android project files found!"
            echo "Contents of app directory:"
            ls -la app/
          else
            echo "ERROR: Android project files were not created!"
            exit 1
          fi
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

      - name: Build Android App
        env:
          BUBBLEWRAP_KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          BUBBLEWRAP_KEY_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        run: |
          # Use bubblewrap Docker container to build the Android project with license acceptance
          echo "y" | docker run --rm -i -v $(pwd):/workspace -w /workspace \
            -e BUBBLEWRAP_KEYSTORE_PASSWORD="${BUBBLEWRAP_KEYSTORE_PASSWORD}" \
            -e BUBBLEWRAP_KEY_PASSWORD="${BUBBLEWRAP_KEY_PASSWORD}" \
            ghcr.io/googlechromelabs/bubblewrap:latest build

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app-release-signed.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: app-release-bundle.aab
