name: Build and Release

on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: 'Is this a pre-release?'
        type: boolean
        default: false

# Add permissions needed for creating releases
permissions:
  contents: write
  packages: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Variables
        run: |
          echo VERSION=$(npm run get-version --silent) >> $GITHUB_ENV
        shell: bash
    
      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install dependencies
        run: npm install --force

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        id: tauri_build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ env.VERSION }}
          releaseName: "Nostria v${{ env.VERSION }}"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: ${{ github.event.inputs.prerelease }}

      # Upload APK as additional release artifact (only need to do this once, so use ubuntu runner)
      - name: Upload APK as release asset
        if: matrix.platform == 'ubuntu-latest'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.tauri_build.outputs.releaseUploadUrl }}
          asset_path: packages/nostria.apk
          asset_name: nostria.apk
          asset_content_type: application/vnd.android.package-archive

      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: artifacts-${{ matrix.platform }}
      #     path: |
      #       target/release/bundle/